const express = require('express');
const nodemailer = require('nodemailer');
const cors = require('cors');
const bodyParser = require('body-parser');

const app = express();
app.use(cors());
app.use(bodyParser.json());

// --- MANUAL CONFIGURATION ---
const MY_EMAIL = "moddy2232@gmail.com"; // Put your email here
const APP_PASSWORD = "kdtx ovfm zzkc yndr"; // Put your gmail app password here
// ----------------------------

// Mock Database (Replace with MongoDB/SQLite for persistence)
const otps = new Map();

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: MY_EMAIL,
        pass: APP_PASSWORD
    }
});

// Endpoint to initiate Login/Signup and send OTP
app.post('/api/auth/init', async (req, res) => {
    const { email, password, type } = req.body;
    const code = Math.random().toString(36).substring(2, 8).toUpperCase();
    
    otps.set(email, { code, password });

    const mailOptions = {
        from: `"Nexus Hoster" <${MY_EMAIL}>`,
        to: email,
        subject: 'Your Nexus Hoster Verification Code',
        text: `Hey welcome to Nexus Hoster\nthis is an automated message from nexushoster\n\nYour code is\n\n${code}\n\nfrom nexushoster\n-qetoo`
    };

    try {
        await transporter.sendMail(mailOptions);
        res.status(200).json({ success: true, message: "OTP Sent" });
    } catch (error) {
        console.error(error);
        res.status(500).json({ success: false, message: "Email failed to send" });
    }
});

// Pterodactyl Integration Mockup
// In a real app, you'd use the Pterodactyl API (Application & Client)
app.post('/api/server/create', async (req, res) => {
    const { name, type, userId } = req.body;
    
    // Logic to call Pterodactyl API:
    // 1. Create user on panel if not exists
    // 2. Create server using correct Egg (Node or Python)
    // 3. Return random password generated by Pterodactyl or manual 5-20 chars
    
    const panelPassword = Math.random().toString(36).slice(-12);
    res.json({ success: true, password: panelPassword });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Nexus Hoster Backend running on port ${PORT}`));
